const COUNTRY_CODE_MAP: Record<string, string> = {
  "United Kingdom": "gb",
  "Switzerland": "ch",
  "Germany": "de",
  "France": "fr",
  "Netherlands": "nl",
  "Belgium": "be",
  "Sweden": "se",
  "Ireland": "ie",
  "Italy": "it",
  "Denmark": "dk",
  "Russian Federation": "ru",
  "Finland": "fi",
  "Norway": "no",
  "Austria": "at",
  "Spain": "es",
  "Portugal": "pt",
  "Czechia": "cz",
  "Poland": "pl",
  "Greece": "gr",
  "Estonia": "ee",
  "Luxembourg": "lu",
  "Lithuania": "lt",
  "Belarus": "by",
  "Slovenia": "si",
  "Hungary": "hu",
  "Iceland": "is",
  "Latvia": "lv",
  "Serbia": "rs",
  "Romania": "ro",
  "Ukraine": "ua",
  "Bulgaria": "bg",
  "Malta": "mt",
  "Croatia": "hr",
  "Bosnia and Herzegovina": "ba",
  "Slovakia": "sk",
  "Cyprus": "cy",
  "Montenegro": "me",
  "North Macedonia": "mk",
  "Albania": "al",
  "Moldova": "md",
  "Andorra": "ad",
  "San Marino": "sm",
  "Liechtenstein": "li",
  "Monaco": "mc",
  "Vatican City": "va",
};

export function getCountryCode(countryName: string): string {
  return COUNTRY_CODE_MAP[countryName] || "eu";
}
